name: pulero_apk
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  path: ^1.9.0
  provider: ^6.1.2
  rename_app: ^1.6.1
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  syncfusion_flutter_calendar: ^27.1.50

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/pulero.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21